export { default as HomeIntro } from './Intro';
export { default as HomeFeatures } from './Features';
export { default as HomeInformation } from './Information';
export { default as HomeSteps } from './Steps';
export { default as HomeInfoBlock } from './InfoBlock';
export { default as HomeInfoBlockAlt } from './InfoBlockAlt';
export { default as HomeStats } from './Stats';
export { default as HomeTestimonials } from './Testimonials';
export { default as HomeFaq } from './Faq';
